apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: edivaldomva/pedelogo-catalogo:v1.0.0
          resources:
            limits:
              memory: 128Mi
              cpu: 500m
          ports:
            - containerPort: 80
              name: http
            - containerPort: 443
              name: https
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /read   
              port: 80
              scheme: HTTP
            timeoutSeconds: 1
            failureThreshold: 3
            periodSeconds: 5
            successThreshold: 3
            initialDelaySeconds: 10
          livenessProbe:
            httpGet:
                path: /health
                port: 80
                scheme: HTTP
            timeoutSeconds: 1
            failureThreshold: 1
            periodSeconds: 5
          envFrom:
            - configMapRef:
                name: api-configmap
          env:
            - name: Mongo_User
              valueFrom:
                  secretKeyRef:
                    key: MONGO_INITDB_ROOT_USERNAME
                    name: mongodb-secret
            - name: Mongo_password
              valueFrom:
                  secretKeyRef:
                    key: MONGO_INITDB_ROOT_PASSWORD
                    name:  mongodb-secret

