apiVersion: v1
kind: Service
metadata:
  name:  api-service
spec:
  selector:
    app:  api
  type:  ClusterIP
  ports:
  - name:  http
    port:  80
    targetPort:  8080
  - name:  https
    targetPort: 443
    port: 443
